const OPENAI_IMAGES_EDIT_URL = process.env.OPENAI_IMAGES_EDIT_URL || 'https://api.openai.com/v1/images/edits';
const OPENAI_IMAGE_MODEL = process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1.5';
const OPENAI_IMAGE_QUALITY = process.env.OPENAI_IMAGE_QUALITY || 'high';

function parseDataUrl(dataUrl) {
  const match = String(dataUrl || '').match(/^data:([^;,]+)?(;base64)?,(.*)$/);
  if (!match) throw new Error('mask_data_url must be a data URL');
  const mime = match[1] || 'image/png';
  const isBase64 = !!match[2];
  const body = match[3] || '';
  const buffer = isBase64 ? Buffer.from(body, 'base64') : Buffer.from(decodeURIComponent(body), 'utf8');
  if (!buffer.length) throw new Error('mask_data_url was empty');
  return { mime, buffer };
}

function buildPrompt({ targetTemperatureC, place, date }) {
  const targetText = Number.isFinite(Number(targetTemperatureC))
    ? `${Number(targetTemperatureC).toFixed(1)} C`
    : 'the requested target temperature';
  return [
    'You are editing a scientific cloud-mask planning image for a cloud seeding UI.',
    'Use the provided cloud mask image as the exact base geometry. Preserve the square composition and alignment exactly.',
    `Goal: suggest cloud-field edits that move the scene toward target temperature ${targetText}.`,
    place ? `Location/sample: ${place}.` : '',
    date ? `Date: ${date}.` : '',
    'Return a clean 2D mask-style overlay, not a photorealistic satellite scene.',
    'Critical preservation rules:',
    '- Every existing cloud must keep its exact current silhouette, boundary, position, size, and internal texture unless it is explicitly marked as removed or modified.',
    '- If an existing cloud is removed or thinned, do NOT redraw or reshape it. Only recolor the same existing cloud pixels red.',
    '- If an existing cloud is modified, do NOT redraw or reshape it. Only recolor the same existing cloud pixels yellow.',
    '- Existing clouds that are not edited must remain grayscale/white and unchanged.',
    '- New clouds are the only regions allowed to change geometry. Draw new cloud additions in green, and make their shape, softness, texture, scale, and grain look like the existing clouds in the input image.',
    '- Do not move existing clouds. Do not warp existing clouds. Do not smooth away their current outlines. Do not invent a new cloud map.',
    'Color-code interventions only:',
    '- red = removal or thinning of existing cloud pixels',
    '- green = newly added cloud pixels',
    '- yellow = modification of existing cloud pixels',
    'Use solid, legible colors while preserving the mask underneath. Do not add text, labels, legends, arrows, numbers, UI chrome, borders, or explanations.',
    'The output should be directly usable as the generated mask preview in the app.'
  ].filter(Boolean).join('\n');
}

export async function generateCloudMaskFallback({
  maskDataUrl,
  targetTemperatureC,
  place,
  date,
}) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error('OPENAI_API_KEY is not configured for AI fallback image generation.');
  }

  const { mime, buffer } = parseDataUrl(maskDataUrl);
  const prompt = buildPrompt({ targetTemperatureC, place, date });
  const form = new FormData();
  form.append('model', OPENAI_IMAGE_MODEL);
  form.append('prompt', prompt);
  form.append('size', process.env.OPENAI_IMAGE_SIZE || '1024x1024');
  form.append('quality', OPENAI_IMAGE_QUALITY);
  form.append('output_format', 'png');
  form.append('image', new Blob([buffer], { type: mime }), 'cloud-mask.png');

  const response = await fetch(OPENAI_IMAGES_EDIT_URL, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
    },
    body: form,
  });
  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    const message = payload?.error?.message || payload?.message || `OpenAI image fallback failed (${response.status})`;
    throw new Error(message);
  }
  let b64 = payload?.data?.[0]?.b64_json;
  if (!b64 && payload?.data?.[0]?.url) {
    const imageResponse = await fetch(payload.data[0].url);
    if (!imageResponse.ok) throw new Error('OpenAI image fallback URL could not be downloaded.');
    const bytes = Buffer.from(await imageResponse.arrayBuffer());
    b64 = bytes.toString('base64');
  }
  if (!b64) throw new Error('OpenAI image fallback returned no image.');

  return {
    generated_mask_data_url: `data:image/png;base64,${b64}`,
    property_maps: {},
    actions: [
      {
        op: 'ai_fallback_overlay',
        remove_color: 'red',
        add_color: 'green',
        modify_color: 'yellow',
      },
    ],
    target_temperature_c: Number.isFinite(Number(targetTemperatureC)) ? Number(targetTemperatureC) : null,
    normalization: 'openai_image_fallback',
    fallback: true,
    fallback_model: OPENAI_IMAGE_MODEL,
    fallback_quality: OPENAI_IMAGE_QUALITY,
    note: 'No RL checkpoint was uploaded; generated by OpenAI image edit fallback from the base cloud mask and target temperature.',
  };
}
